### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by mathematicalmichael** [ml-starter-packs/ml-monorepo#2]
- [ ] first version just sticks to video center
- [ ] given more than one face, find the centroid
- [ ] given a single face, find it (use some test image for `pytest`?)
- [ ] given no face, stick to center
